name: Create OSP Linux images
on: 
  release:
    types: [released]
  pull_request:

jobs:
  build:
    strategy:
        matrix:
            r_version: [3.6.3] #[3.6.3, 4.1.0]
            os_version: [centos7, bionic]
    runs-on: ubuntu-latest
    steps:
      - name: tag name
        id: tag_name
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF##*/}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .github/workflows/Dockerfile
          build-args: |
            r_version=${{ matrix.r_version }}
            os_version=${{ matrix.os_version }}
          push: ${{ github.event_name == 'release' }}
          tags: |
            ghcr.io/open-systems-pharmacology/ospsuite_10.0-reportingengine_1.2-r${{ matrix.r_version }}-${{ matrix.os_version }}:latest
#            ghcr.io/open-systems-pharmacology/ospsuite_10.0-reportingengine_1.2-r${{ matrix.r_version }}-${{ matrix.os_version }}:${{ steps.tag_name.outputs.SOURCE_TAG}}
